### PR TITLE
Add initial files for Exe 1

### PR DESCRIPTION
**Pull request by Reyes-PaulAngelo**
Add initial files for the exercise 1.

### CODE REVIEW

**Review by barrantes-sofiaanne — CHANGES_REQUESTED** [review]
Hello Mr Paul Reyes, I would like you follow first the step 2 of the instructions before merging.

**Comment by Reyes-PaulAngelo** [comment]
> Hello Mr Paul Reyes, I would like you follow first the step 2 of the instructions before merging.

**Comment by Reyes-PaulAngelo** [comment]
> > Hello Mr Paul Reyes, I would like you follow first the step 2 of the instructions before merging.

Thank you Ms. Sofia, this is noted!

**Review by barrantes-sofiaanne — APPROVED** [review]
This is good to go! You may merge this to the main branch

**Review by barrantes-sofiaanne — APPROVED** [review]
This is also good and you may merge it to the main branch

**Comment by Reyes-PaulAngelo** [comment]
Thank you, Ms. Sofia

**Pull request merged**
